### ISSUE TITLE
sub-domain request

### ISSUE THREAD

**Issue by govvin** [sotm-asia/tasking-manager#1]
We're setting up a new tasking manager instance, and we would like to make the resource available to interested OSM communties in Asia who don't run their own instance, or would like to participate in this instance.

@mapconcierge 
Would it be possible to to request a sub-domain for this purpose?
- [ ] tasks.openstreetmap.asia  (preferred)
- [ ] tasks.stateofthemap.asia

**Comment by mapconcierge** [comment]
＞  @govvin 
I found this message now. Okay!! Wait a moment...  So sorry...

**Comment by mapconcierge** [comment]
＞  @govvin 

 I've understood. "openstreetmap.aisa" domain is maintained by Satoshi IIDA as OSMFJ.


--
 # Whois  Result

Domain Name: OPENSTREETMAP.ASIA
Registry Domain ID: D107700000000961494-AGRS
Registrar WHOIS Server: whois.discount-domain.com
Registrar URL: http://www.onamae.com
Updated Date: 2017-07-06T15:45:04Z
Creation Date: 2008-07-31T02:43:42Z
Registry Expiry Date: 2019-07-31T02:43:42Z
Registrar Registration Expiration Date:
Registrar: GMO Internet, Inc. d/b/a Onamae.com
Registrar IANA ID: 49
Registrar Abuse Contact Email:
Registrar Abuse Contact Phone:
Reseller:
Domain Status: ok https://icann.org/epp#ok
Registry Registrant ID: C18207992-AGRS
Registrant Name: Hiroshi Miura
Registrant Organization: Hiroshi Miura
Registrant Street: 1-3-3-911 Kamiya
Registrant City: Kita-ku
Registrant State/Province: Tokyo
Registrant Postal Code: 115-0043
Registrant Country: JP
Registrant Phone: +81.369154373
Registrant Phone Ext:
Registrant Fax:
Registrant Fax Ext:
Registrant Email: nyampire*
Registry Admin ID: C18207993-AGRS
Admin Name: Satoshi IIDA
Admin Organization: OpenStreetMap Foundation Japan
Admin Street: 1-3-3-911 Kamiya
Admin City: Kita-ku
Admin State/Province: Tokyo
Admin Postal Code: 115-0043
Admin Country: JP
Admin Phone: +81.369154373
Admin Phone Ext:
Admin Fax:
Admin Fax Ext:
Admin Email: nyampire*
Registry Tech ID: C18207994-AGRS
Tech Name: Satoshi IIDA
Tech Organization: OpenStreetMap Foundation Japan
Tech Street: 1-3-3-911 Kamiya
Tech City: Kita-ku
Tech State/Province: Tokyo
Tech Postal Code: 115-0043
Tech Country: JP
Tech Phone: +81.369154373
Tech Phone Ext:
Tech Fax:
Tech Fax Ext:
Tech Email: nyampire*
Name Server: DNS1.ONAMAE.COM
Name Server: DNS2.ONAMAE.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2018-01-11T03:02:58Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

Access to WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the registry database. The data in this record is provided by The Registry Operator for informational purposes only, and accuracy is not guaranteed. This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to: (a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. Registry Operator reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

**Comment by mapconcierge** [comment]
Oh, I don't have admin permission on this GitHub Organization. 
＞  do you have ? and please add admin permission to me. @govvin @maning @geohacker

**Comment by mapconcierge** [comment]
Please add @nyampire

https://github.com/nyampire

https://github.com/orgs/osmfj/people/nyampire

**Comment by nyampire** [comment]
Hello from Japan.
I guess the WHOIS information is not registered correctly.

Anyway, the domain is owned by OSMFJ (as organization).
I will ask them to make sub-domain.
Please tell me the IP address to be assigned if it is fixed.

**Comment by mapconcierge** [comment]
Thanks, @nyampire

**Comment by govvin** [comment]
Thank you @nyampire , @mapconcierge ! :bowing_man: 

I'll get back to you on this ASAP.

**Comment by maning** [comment]
> Oh, I don't have admin permission on this GitHub Organization.

Done @mapconcierge 

> Please add @nyampire

Done!

**Comment by mapconcierge** [comment]
Thanks, @maning !!

**Comment by nyampire** [comment]
@maning Thank you 👍 

@govvin I found my account for that. (Completely forgot it!) I may set "tasks.openstreetmap.asia".

**Comment by maning** [comment]
[Sub-domain](http://tasks.openstreetmap.asia/) is ready any next actions here?

**Comment by govvin** [comment]
Thank you for the reminder @maning . Unfortunately, there had been a change of plans and there is no movement from my end at the moment. 

The original idea was to host a tasking manager (as part of my Kaart projects) and make the TM also available for other Asian communities.  This could have been a repository of the projects we're running in the Philippines.

We could have pursued this, had we gotten a green signal for the sub-domain earlier. Now, we realized our project scope is too small to warrant its own instance so we decided to just run the projects under the HOT instance, at least for now.  

If ever we would require a separate TM instance soon, I'd like to revisit this. Perhaps any of you would like to run a TM here for now?

Sorry for the bother. I'll close this now, and relinquish first dibs on the sub-domain. :grin:
